### PR TITLE
cleaned up output of state machine

### LINKED ISSUE #16: Cleanup State Machine Output
Startgate objective prints out a ton of stuff, clean it up

### PR DESCRIPTION
**Pull request by flamma7**
State Machine no longer blasts terminal with messages & output is formatted nicely
Solved Startgate aborting problem by only updating (and thus triggering a replan) if the new pose is outside of threshold of distance from the original pose. Closes #16

### CODE REVIEW

**Comment by flamma7** [comment]
Also wait for the waypoint navigator only once before running instead of inside each objective initialized

**Comment by DrYerzinia** [comment]
Does that actually affect the functionally of anything, like a compile error or a more clear error if you run the statemachine without the common package

**Comment by belgiumkansas** [comment]
i believe it will through an error if you do a clean build. the reason being there is no way to reference that module in the python_paths unless its explicitly reference in the package.

**Comment by belgiumkansas** [comment]
Plus its a good habit to include all the needed dependency references in your catkin environment

**Pull request merged**
